# Project
version = 1.0
group = net.createmod.ponder

# Common
minecraft_version = 1.20.1
librarian_version = 1.+
parchment_version = 2023.09.03
use_parchment = true
flywheel_version = 1.0.0-215
flywheel_version_range = [1.0.0,2.0)

# Forge
forge_version = 47.2.6
forge_version_range=[47,)
minecraft_version_range=[1.20.1, 1.21)

# Fabric https://fabricmc.net/develop/
loom_version = 1.10.+
fabric_version = 0.92.3+1.20.1
fabric_loader_version = 0.16.9
port_lib_version = 2.3.8+1.20.1
port_lib_modules = base,models

# Mod options
mod_name = Ponder
mod_author = simibubi, Pepper, zelophed
mod_credit = Special Thanks to IThundxr, Jozufozu, Snownee, gamez7, tterrag and Grimmauld
mod_id = ponder
project_id = ponder
mod_homepage = https://github.com/Creators-of-Create/Ponder
mod_source = https://github.com/Creators-of-Create/Ponder
mod_issues = https://github.com/Creators-of-Create/Ponder/issues
mod_description = Visual in-Game Documentation
mod_license = MIT

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
